<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { width: 100%; max-width: 800px; margin: 0 auto; padding: 20px; }
        .header { background: #1e3a8a; color: #fff; padding: 15px; text-align: center; border-radius: 5px 5px 0 0; }
        h1, h2, h3 { margin-top: 20px; color: #1e3a8a; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background-color: #f8fafc; font-weight: bold; }
        .stat-box { display: inline-block; width: 30%; background: #f1f5f9; padding: 15px; margin: 1%; text-align: center; border-radius: 5px; }
        .stat-box h2 { margin: 0; font-size: 24px; color: #0f172a; }
        .stat-box p { margin: 5px 0 0; font-size: 14px; color: #64748b; }
        .footer { margin-top: 30px; font-size: 12px; color: #666; text-align: center; border-top: 1px solid #ddd; padding-top: 15px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>JSHB Daily Activity Report</h2>
            <p>Date: {{ $reportDate }}</p>
        </div>

        <h3>1. Overall Application Stats</h3>
        <div>
            <div class="stat-box">
                <h2>{{ $reportData['total_created'] }}</h2>
                <p>New Applications Created</p>
            </div>
            <div class="stat-box">
                <h2>{{ $reportData['total_completed'] }}</h2>
                <p>Applications Completed</p>
            </div>
            <div class="stat-box">
                <h2>{{ $reportData['total_docs_generated'] }}</h2>
                <p>Documents Generated</p>
            </div>
        </div>

        <h3>2. Engineer Performance Report</h3>
        <p>Total movements processed yesterday: <strong>{{ $reportData['total_movements'] }}</strong></p>
        <table>
            <thead>
                <tr>
                    <th>Engineer Name</th>
                    <th>Role</th>
                    <th>Application Movements</th>
                    <th>Correspondence Letters Generated</th>
                </tr>
            </thead>
            <tbody>
                @forelse($reportData['engineer_report'] as $eng)
                    <tr>
                        <td>{{ $eng['name'] }}</td>
                        <td>{{ $eng['role'] }}</td>
                        <td>{{ $eng['movements'] }}</td>
                        <td>{{ $eng['letters'] }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="4" style="text-align:center;">No engineer activity recorded yesterday.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <h3>3. Bypass Requests Report</h3>
        <table>
            <thead>
                <tr>
                    <th>Application No</th>
                    <th>Requested By</th>
                    <th>Sent To (Bypassed)</th>
                    <th>Reason</th>
                </tr>
            </thead>
            <tbody>
                @forelse($reportData['bypass_report'] as $bypass)
                    <tr>
                        <td>{{ $bypass['app_no'] }}</td>
                        <td>{{ $bypass['requested_by'] }}</td>
                        <td>{{ $bypass['sent_to'] }}</td>
                        <td>{{ $bypass['reason'] }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="4" style="text-align:center;">No applications were bypassed yesterday.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <div class="footer">
            <p>This is an automated system report generated by JSHB Batch Scheduler.</p>
        </div>
    </div>
</body>
</html>
